image: ruby:2.4.4-slim  #"registry.gitlab.com/rpadovani/rpadovani.com:latest" # Custom Ruby image, replace with whatever you want
stages:
  - build
  - deploy
  - deploy-test

# variables:
#  AWS_DEFAULT_REGION: us-west-2  # The region of our S3 bucket
#  BUCKET_NAME: test.wsealug.net  # Your bucket name

cache:
  paths:
    - vendor

buildJekyll:  # A job to build the static website - replace it with your build methods
  stage: build
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends g++ make 
    - bundle install --path=vendor/
    - bundle exec jekyll build 
  artifacts:
    paths:
      - _site/  # This is what we want to publish, replace with your `dist` directory

deploy:
  image: python:3.6-slim  # "python:latest"  # We use python because there is a well-working AWS Sdk
  stage: deploy
  dependencies:
    - buildJekyll      # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
  before_script:
    - pip install awscli # Install the SDK
  script:
    - aws s3 sync _site s3://$S3_BUCKET_NAME
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
    - echo "DEPLOYED SUCCESSFULLY"
  only:
    - master

deploy-test:
  image: python:3.6-slim  # "python:latest"  # We use python because there is a well-working AWS Sdk
  stage: deploy-test
  dependencies:
    - buildJekyll      # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
  before_script:
    - pip install awscli # Install the SDK
  script:
    - aws s3 sync _site s3://$S3_BUCKET_NAME_TEST
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_TEST --paths '/*'
    - echo "DEPLOYED SUCCESSFULLY TO TEST"
  tags:
    - testdeploy
  only:
    - tags 
